name: voila
channels:
  - conda-forge
dependencies:
  - ipyvolume
  - bqplot
  - scipy
  - ipympl
  - voila=0.1.21
  - ipympl
  - sklearn
  - time
  - gensim
  - ipywidgets
  - codecs
  - IPython.display
